schema = 3

[mod]
  [mod."charm.land/bubbles/v2"]
    version = "v2.0.0"
    hash = "sha256-MhBifn4m+BTZrO8twl9jutDFWMVzWvfYLsJfQc2zeg4="
  [mod."charm.land/bubbletea/v2"]
    version = "v2.0.1"
    hash = "sha256-mJmViMvgdOsa+FiFPmly5HSBuHxwvDw1fAvon6VpD4I="
  [mod."charm.land/lipgloss/v2"]
    version = "v2.0.0"
    hash = "sha256-O78AzqA19r2N7DpRwj7pCk57Spqo8FkdD1J8frGQqoc="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.4.2"
    hash = "sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw="
  [mod."github.com/charmbracelet/ultraviolet"]
    version = "v0.0.0-20260303162955-0b88c25f3fff"
    hash = "sha256-jszDf3Y15JhcH+zWFONJTrZGouEtHEVtYNg7MKcLSFg="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.11.6"
    hash = "sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.2"
    hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
  [mod."github.com/charmbracelet/x/termios"]
    version = "v0.1.1"
    hash = "sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds="
  [mod."github.com/charmbracelet/x/windows"]
    version = "v0.2.2"
    hash = "sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.11.0"
    hash = "sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.7.0"
    hash = "sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.21"
    hash = "sha256-JU+ZijAu0o+5jzfLC8ytQzxIAKYr5ow3nCjFf0ehpiA="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.41.0"
    hash = "sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
